version: '3.1'

services:
  db:
    image: mariadb:latest
    container_name: mariadb-server
    environment:
      MYSQL_ROOT_PASSWORD: password         # Password da amministratore del database
      MYSQL_DATABASE: motor-mate          # Nome del database da creare
      MYSQL_USER: user                   # Nome utente per il database
      MYSQL_PASSWORD: resu               # Password per l'utente del database
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
